# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Onedaystock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='stockPrediction.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Oneyearstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('open', models.FloatField()),
                ('pricelow', models.FloatField()),
                ('close', models.FloatField()),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='stockPrediction.Company')),
            ],
        ),
    ]
