# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockPrediction', '0002_auto_20160426_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedaystock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oneyearstock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
